FROM domaindrivenarchitecture/dda-httpd-crate:SNAPSHOT

# workaround till new serverspec is available
RUN apt-get install net-tools curl -y

RUN curl -L -o /app/serverspec.jar https://github.com/DomainDrivenArchitecture/dda-serverspec-crate/releases/download/1.2.1/dda-serverspec-crate-1.2.1-standalone.jar
COPY integration/docker/test/serverspec-single.edn /app/serverspec.edn

RUN java -jar /app/serverspec.jar /app/serverspec.edn
