dist: trusty
language: clojure

services:
  - docker

stages:
  - build

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure: "6IgL6d4XB7lpZPK10HJFDfzwJ9NE642My1IWWKGUABbT8Zlme3QlMSC8vGLQcr0Um0lCwaNpGi1oy++h02libAEsdX/EfiL9u0MKBHs8CprAcxZrHI6fTSOSICXmQtlbJLMEzoX2WKrC+wZKEzeRhG0NywunHIv5P5Pf/FNppheUaor4LSGh5UfvYSidKOZzhNJnaSsKoBmYZ5qTFHrU2tJq3jRx+yoerSl7Vpn2El16V/t/5kxLgetNgx511vwWhopQgCy0bZmjQzgrMmrZ+Rwz+y/OFPZI+ndWmqLc1T9nBDqx1MmjSSA2cUULtIAoULYebo67C3NLhmdQ4brnC2DouujLbp+IY888fbZsprqSZLM02fRlYj2mFXhfcy14FHWIDCntrKY42EQIuSKNAEp2DdBKwkm/5lLIaQ7FQ1asVkfCIgUJPx01esKxyKgRdT5vhvvWz83ZyPRDwJQmkEC82VZGdXcZcuahiTiIwA85S+Nez4L+0IeEfeTVe3jk2BTGWi26bM8jn4cwFXYfJiVkMlun8UTytI8BYPmT5ozexOCcmaLYr/3CgBGWLEvHbmWQUUHZGPYzdgrahgZ+tDA721LCQW7UzvSGEHI5qomgl14N9JJHtOTc6+uaQYFGRdpS6VYiF3DvUmFdgBToZA65lFS5oEIBiLMaPX5n8GA="

jobs:
  include:
    - stage: build
      script:
        - # build
        - lein test
        - lein uberjar
        - md5sum target/dda-httpd-standalone.jar > target/dda-httpd-standalone.jar.md5
        - # create docker image single static
        - docker build -t dda-httpd-crate --file integration/docker/single_static/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-httpd-crate-test --file integration/docker/single_static/test/Dockerfile .
        - # create docker image single static
        - docker build -t dda-httpd-crate --file integration/docker/single_proxy/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-httpd-crate-test --file integration/docker/single_proxy/test/Dockerfile .
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          api_key:
            secure: "gsggPDqP7HcU4ZC7l+h5Gxzeb2PLipe5owgZAGxJgh5bg2Q5gJJXmzX5NiK7g7EUQWaOQaOV8HosHarmKoHm4CzwcpDHRbBDdumn09rgbI0J9miuy2W+CLX5zV9H+vvUYgPYdyDsNEHH6Y3MYywx/QLa/ZVyZdobvX3lWuNtF+awwtvTFuUjPFiktNsHulasXva1T1i5gou2zbo3NiXeKpv57kA8526kCk38YUNWuEHxKKpxWqzYXVXpIo3aijCHHjCU/yHh8bo3Q4v6hu3noZjOa9UTISRerCVpB7tKA4O8TkwBoYDpVbHJ20qb/C6HFJFOaLNXzxt8oskrwR4R5TPisqDsTukbJeGdc4lAhml1m6sR8huwg9oGCEqr6JcUZEwG8XPP7uZGQn5x/o0QaKhi+FHL2vWvPJTPSsLZ4/CK80qZ6DXzQ3hgH4TdejgR94xO0wiVhPsDDSHaz9kOJAZH435oO0FJokD0SslL8QEItoZ8Mce99t3qMn6fjTLpId2U+rge23D+AKFq0D6QByUYxgg8rL8Sc/YbJol1DYL005eD1286GKXQYZuREOutMqbNs4RvpgTEzrEBlqbMZgPBfLOardnMRfBVwnlMqWTqE2EtxTcOUsg+ajtDlJaXG58JVPCz6ovZuJr4yvtXwZlBQCDcQjDNw/I1i0S8OfI="
          file:
            - target/dda-httpd-standalone.jar
            - target/dda-httpd-standalone.jar.md5
        - provider: script
          skip_cleanup: true
          on:
            tags: true
          script: bash integration/docker/publish.sh dda-httpd-crate
